<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <NoWarn>$(NoWarn);WFAC010</NoWarn>
    <RootNamespace>ERHandlerManager</RootNamespace>
    <AssemblyName>EldenRingHandlerManager</AssemblyName>
    <Version>1.1.0</Version>
    <FileVersion>1.1.0</FileVersion>
    <InformationalVersion>1.1.0</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Include="CHANGELOG.md" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>